name: Rust

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_GAME_SDK_PATH: home/runner/discord-lib/
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}$DISCORD_GAME_SDK_PATH/lib/x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Downloading lib
      run: wget -O ~/discord_lib.zip https://dl-game-sdk.discordapp.net/latest/discord_game_sdk.zip
    - name: Unzip
      run: unzip -d ~/discord-lib/ ~/discord_lib.zip
    - name: Upload lib
      uses: actions/upload-artifact@v4
      with:
        name: discord-game-sdk
        path: |
          ~/discord-lib
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
