name: Rust

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_GAME_SDK_PATH: $HOME/discord-lib/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Downloading lib
      run: wget -O ~/discord_lib.zip https://dl-game-sdk.discordapp.net/latest/discord_game_sdk.zip
    - name: Unzip
      run: unzip -d ~/discord-lib/ ~/discord_lib.zip
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
